pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'devops:latest'

steps:
- script: dotnet restore
  displayName: 'Restoring Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building Project'

- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- script: docker build --no-cache -f Dockerfile -t $1988dojima/$balatro-backend .
  displayName: 'Building Docker Image'

- script: |
    docker login -u $1988dojima -p $16082016steam
    docker push $1988dojima/$balatro-backend
  displayName: 'Sending Image to Docker Hub'