services:
  backend:
    build: ./backend
    container_name: todo_backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: todo_frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: https://spamwarelist.azurewebsites.net/api-docs/
